services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: lab1
      POSTGRES_USER: lab
      POSTGRES_PASSWORD: lab
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab -d lab1"]
      interval: 5s
      timeout: 3s
      retries: 10